### ISSUE TITLE
ivf_pq range search on glove is 100% lower than expectation 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/knowhere#334]
ivf_pq range search latency is lower especially when nprobe is 512.
m=8, nbits=8
in ref_log it is 4.8s when nrpbe=512, so a reasonable latency in ci shall be <6s
`ivf_pq range search on glove latency: [0.1639, 0.22, 0.1808, 0.3279, 0.4638, 0.8545, 1.6019, 3.0346, 5.8834, 11.6323]`

**Comment by cydrain** [comment]
[59.149 s] glove-200-angular-range | IVF_PQ | nlist=1024, radius=0.520
================================================================================
  nprobe =    1, nq = 10000, elapse =  0.137s, R@ = 0.2880, A@ = 0.3964
  nprobe =    2, nq = 10000, elapse =  0.125s, R@ = 0.4277, A@ = 0.4041
  nprobe =    4, nq = 10000, elapse =  0.154s, R@ = 0.5652, A@ = 0.4143
  nprobe =    8, nq = 10000, elapse =  0.170s, R@ = 0.6417, A@ = 0.4181
  nprobe =   16, nq = 10000, elapse =  0.243s, R@ = 0.6695, A@ = 0.4203
  nprobe =   32, nq = 10000, elapse =  0.414s, R@ = 0.6749, A@ = 0.4212
  nprobe =   64, nq = 10000, elapse =  0.684s, R@ = 0.6766, A@ = 0.4217
  nprobe =  128, nq = 10000, elapse =  1.380s, R@ = 0.6770, A@ = 0.4218
  nprobe =  256, nq = 10000, elapse =  2.608s, R@ = 0.6772, A@ = 0.4218
  nprobe =  512, nq = 10000, elapse =  4.785s, R@ = 0.6772, A@ = 0.4218
================================================================================

@yanliang567
I see all of your runtime is about 2 times of the runtime in my ref_logs
nprobe = 128, 1.380s VS. 3.0346
nprobe = 256, 2.608s VS. 5.8834
nprobe = 512, 4.785s VS. 11.6323
and when 'nprobe' doubled, runtime also doubled.
So I think the runtime difference is caused by hardware, it's acceptable.

**Comment by yanliang567** [comment]
okay, close and update the test baseline accordingly.
